/**
 * Types are derived from the schema customization in gastby-node.js
 * and generated by running `gatsby develop` after editing the schema.
 * These generated types are accessed on the Queries object in the global
 * namespace as in Queries.DataByIdQuery for a page query called DataByIdQuery.
 * 
 * To ensure data safety and avoid excess non-null assertions,
 * derived non-nullable types are added here, and used in conjuction with
 * resolvers that ensure fields are present. 
 */
export type IdeaPostQuery = Queries.IdeaPostByIDQuery;
export type IdeaPostNode = NonNullable<IdeaPostQuery["markdownRemark"]>;
export type IdeaFrontmatter = NonNullable<IdeaPostNode["frontmatter"]>;

export type MaterialsAndMethods = NonNullable<IdeaFrontmatter["materialsAndMethods"]>;
export type CellLine = MaterialsAndMethods["cellLines"][number];
export type SoftwareTool = MaterialsAndMethods["software"][number];
