import { IGatsbyImageData } from "gatsby-plugin-image";

/**
 * Types are derived from the schema customization in gatsby-node.js
 * and generated by running `gatsby develop` after editing the schema.
 * These generated types are accessed on the Queries object in the global
 * namespace as in Queries.DataByIdQuery for a page query called DataByIdQuery.
 *
 * To ensure data safety and avoid excess non-null assertions,
 * derived non-nullable types are added here, and used in conjunction with
 * resolvers that ensure fields are present.
 *
 * After updating schema customization, run `gatsby develop` to regenerate types.
 */
export type IdeaPostQuery = Queries.IdeaPostByIDQuery;
export type IdeaPostNode = NonNullable<IdeaPostQuery["ideaPost"]>;

export type IdeasForTags =
    Queries.AllIdeasForTagsQuery["allMarkdownRemark"]["edges"];

export type PreliminaryFindings = NonNullable<
    IdeaPostNode["preliminaryFindings"]
>;
export type Figure = NonNullable<
    NonNullable<IdeaPostNode["preliminaryFindings"]>["figures"]
>[number];

export type ResourceTemplateQuery = Queries.ResourcesByIdQuery;
export type ResourceNode = Omit<
    NonNullable<NonNullable<ResourceTemplateQuery>["resource"]>,
    "id"
>;

/**
 * Other utility types
 */

export interface ChildImageSharp {
    gatsbyImageData: IGatsbyImageData;
}
