/**
 * Types are derived from the schema customization in gastby-node.js
 * and generated by running `gatsby develop` after editing the schema.
 * These generated types are accessed on the Queries object in the global
 * namespace as in Queries.DataByIdQuery for a page query called DataByIdQuery.
 * 
 * To ensure data safety and avoid excess non-null assertions,
 * derived non-nullable types are added here, and early returns
 * or other handling are used in templates and pages.
 * 
 * Custom types or fallbacks for null fields can also be used,
 * but basing our query and prop types on the typegen output
 * ensures that our types are at least in sync with each other,
 * and gets the most out of TS and the IDE when using them.
 * 
 * The general pattern is to access a type on the Queries object
 * in the global namespace, and then make N
 */
export type IdeaPostQuery = Queries.IdeaPostByIDQuery;
export type IdeaPostNode = NonNullable<IdeaPostQuery["markdownRemark"]>;
export type IdeaFrontmatter = NonNullable<IdeaPostNode["frontmatter"]>;

export type MaterialsAndMethods = NonNullable<IdeaFrontmatter["materialsAndMethods"]>;
export type CellLine = MaterialsAndMethods["cellLines"][number];
export type SoftwareTool = MaterialsAndMethods["software"][number];