type MarkdownRemarkFields {
    slug: String!
}

type MarkdownRemark implements Node {
    fields: MarkdownRemarkFields!
    frontmatter: Frontmatter!
}

type Frontmatter {
    date: Date @dateformat
    description: String
    draft: Boolean
    tags: [String!]
    title: String!
}

type ResourceLink {
    name: String!
    url: String!
    description: String
}

type Resource implements Node {
    date: Date @dateformat
    description: String
    draft: Boolean
    file: String
    name: String
    links: [ResourceLink!]
    readmeLink: String
    slug: String!
    status: String
    tags: [String!]
    type: String
}

type IdeaPost implements Node {
    authors: [String!]!
    date: Date @dateformat
    description: String
    draft: Boolean
    introduction: String
    nextSteps: String
    preliminaryFindings: PreliminaryFindings
    program: [String!]!
    publication: String
    relatedIdeas: [IdeaPost!]!
    resources: [Resource!]!
    slug: String!
    tags: [String!]!
    title: String!
}

type PreliminaryFindings {
    figures: [ImgWithCaption!]!
    summary: String!
}

type ImgWithCaption @dontInfer {
    caption: String
    file: File @fileByRelativePath
    type: String!
    url: String
}
