type MarkdownRemarkFields {
    slug: String!
}

type MarkdownRemark implements Node {
    frontmatter: Frontmatter!
    fields: MarkdownRemarkFields!
}

type Frontmatter {
    date: Date @dateformat
    title: String!
    description: String
    draft: Boolean
    tags: [String!]
}

type Resource implements Node {
    slug: String!
    name: String
    type: String
    description: String
    link: String
    readmeLink: String
    file: String
    status: String
    date: Date @dateformat
    tags: [String!]
    draft: Boolean
}

type IdeaPost implements Node {
    slug: String!
    date: Date @dateformat
    title: String!
    description: String
    draft: Boolean
    tags: [String!]!
    authors: [String!]!
    nextSteps: String
    program: [String!]!
    publication: String
    introduction: String
    resources: [Resource!]!
    relatedIdeas: [IdeaPost!]!
    preliminaryFindings: PreliminaryFindings
    }

type PreliminaryFindings {
    summary: String!
    figures: [ImgWithCaption!]!
}

type ImgWithCaption @dontInfer {
    type: String!
    url: String
    file: File @fileByRelativePath
    caption: String
}