name: CI
env:
    NODE_VERSION: "22.x"

on:
    pull_request:
        branches:
            - main

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/setup
            - run: npm run lint

    format:
        name: Format check
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/setup
            - run: npm run formatCheck

    typecheck:
        name: Type check
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/setup
            - run: npm run typeCheck

    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/setup
            - run: npm test
