name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: AllenCell/reusable-workflows/.github/workflows/setup_npm.yml@55c2e4597381e209128d85c20b60c5509f374e55
    with: 
      node-version: "24.x"
      npm-version: "11.9.0"