name: Setup packages
env:
    NODE_VERSION: "22.x"

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 #v6.2.0
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"
      - name: Install npm at specific version
        run: yarn install --frozen-lockfile
      - name: Install dependencies
        run: npm ci