name: Call a reusable workflow

on:
  pull_request:
    branches:
      - all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: AllenCell/reusable-workflows/.github/workflows/yarn_lint.yml@5322e0b6e03a7413a53fd55501a97e1ab7d84aae